import React, { useState, useEffect } from 'react';
import { Course, Lesson } from '../../types';
import {
  FileText,
  Save,
  Download,
  Copy,
  Check,
  Sparkles,
  Clock,
  Trash2,
  Bold,
  List,
  Code,
  Heading2,
  Share2,
} from 'lucide-react';

interface LessonStudentNotesProps {
  course: Course;
  currentLesson: Lesson;
  initialContent?: string;
  onAutoGeneratedNotesRequested?: () => void;
}

export const LessonStudentNotes: React.FC<LessonStudentNotesProps> = ({
  course,
  currentLesson,
  initialContent,
  onAutoGeneratedNotesRequested,
}) => {
  const storageKey = `academia_notes_${course.id}_${currentLesson.id}`;

  const [notes, setNotes] = useState<string>(() => {
    if (initialContent) return initialContent;
    const saved = localStorage.getItem(storageKey);
    if (saved) return saved;
    return `### 📝 Mes notes sur : ${currentLesson.title}\n\n- Points à approfondir :\n- Questions pour le formateur :\n`;
  });

  const [lastSavedTime, setLastSavedTime] = useState<string>('À l\'instant');
  const [copied, setCopied] = useState(false);

  // Sync when lesson changes or when external note inserted
  useEffect(() => {
    if (initialContent) {
      setNotes(initialContent);
    } else {
      const saved = localStorage.getItem(storageKey);
      if (saved) {
        setNotes(saved);
      } else {
        setNotes(`### 📝 Mes notes sur : ${currentLesson.title}\n\n- Points à approfondir :\n- Questions pour le formateur :\n`);
      }
    }
  }, [currentLesson.id, storageKey]);

  // Auto-save on change
  const handleNotesChange = (val: string) => {
    setNotes(val);
    try {
      localStorage.setItem(storageKey, val);
      setLastSavedTime(new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }));
    } catch (e) {
      console.warn('Erreur de sauvegarde locale', e);
    }
  };

  const insertFormatting = (prefix: string, suffix: string = '') => {
    setNotes((prev) => prev + `\n${prefix} ` + suffix);
  };

  const insertTimestamp = () => {
    const timeStampStr = `⏱️ [Point Clé] `;
    setNotes((prev) => prev + `\n\n${timeStampStr}`);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(notes);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([notes], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `Notes_${currentLesson.title.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleClear = () => {
    if (window.confirm('Voulez-vous réinitialiser vos notes pour cette leçon ?')) {
      const empty = `### 📝 Mes notes sur : ${currentLesson.title}\n\n`;
      setNotes(empty);
      localStorage.removeItem(storageKey);
    }
  };

  const wordCount = notes.trim().split(/\s+/).filter(Boolean).length;

  return (
    <div className="space-y-4">
      {/* Top action bar: formatting tools & autosave indicator */}
      <div className="flex flex-wrap items-center justify-between gap-2 p-2.5 rounded-xl bg-slate-50 border border-slate-200">
        <div className="flex items-center gap-1">
          <button
            onClick={() => insertFormatting('###', '')}
            className="p-1.5 rounded-lg hover:bg-white text-slate-700 hover:text-slate-950 text-xs font-bold border border-transparent hover:border-slate-200 transition-colors"
            title="Titre"
          >
            <Heading2 className="w-4 h-4" />
          </button>
          <button
            onClick={() => insertFormatting('- ', '')}
            className="p-1.5 rounded-lg hover:bg-white text-slate-700 hover:text-slate-950 text-xs font-bold border border-transparent hover:border-slate-200 transition-colors"
            title="Liste à puces"
          >
            <List className="w-4 h-4" />
          </button>
          <button
            onClick={() => insertFormatting('```typescript\n// Votre code ici\n```', '')}
            className="p-1.5 rounded-lg hover:bg-white text-slate-700 hover:text-slate-950 text-xs font-bold border border-transparent hover:border-slate-200 transition-colors"
            title="Bloc de code"
          >
            <Code className="w-4 h-4" />
          </button>
          <button
            onClick={insertTimestamp}
            className="px-2 py-1 rounded-lg hover:bg-white text-slate-700 hover:text-slate-950 text-xs font-semibold border border-transparent hover:border-slate-200 transition-colors flex items-center gap-1"
            title="Insérer un repère temporel"
          >
            <Clock className="w-3.5 h-3.5 text-sky-600" />
            <span className="hidden sm:inline">Repère</span>
          </button>

          {onAutoGeneratedNotesRequested && (
            <button
              onClick={onAutoGeneratedNotesRequested}
              className="px-2.5 py-1 rounded-lg bg-sky-100 hover:bg-sky-200 text-sky-800 text-xs font-bold flex items-center gap-1 transition-all"
            >
              <Sparkles className="w-3.5 h-3.5 text-sky-600" />
              <span>Générer avec l'IA</span>
            </button>
          )}
        </div>

        <div className="flex items-center gap-2">
          <span className="text-[11px] text-slate-500 font-medium">
            {wordCount} mots • Sauvegardé ({lastSavedTime})
          </span>

          <button
            onClick={handleCopy}
            className="p-1.5 rounded-lg hover:bg-white text-slate-600 hover:text-slate-900 border border-slate-200 bg-white text-xs flex items-center gap-1 shadow-2xs"
            title="Copier le texte"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={handleDownload}
            className="p-1.5 rounded-lg hover:bg-white text-slate-600 hover:text-slate-900 border border-slate-200 bg-white text-xs flex items-center gap-1 shadow-2xs"
            title="Télécharger en Markdown (.md)"
          >
            <Download className="w-3.5 h-3.5" />
          </button>

          <button
            onClick={handleClear}
            className="p-1.5 rounded-lg hover:bg-rose-50 text-slate-400 hover:text-rose-600 transition-colors"
            title="Effacer les notes"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Textarea Editor */}
      <div className="relative">
        <textarea
          value={notes}
          onChange={(e) => handleNotesChange(e.target.value)}
          rows={10}
          placeholder="Écrivez vos réflexions, vos questions et vos points mémorables..."
          className="w-full p-4 rounded-2xl bg-white border border-slate-200 text-slate-800 text-xs sm:text-sm font-mono leading-relaxed focus:outline-none focus:border-sky-500 shadow-2xs resize-y"
        />
      </div>

      <div className="p-3 rounded-xl bg-sky-50/70 border border-sky-200/80 text-[11px] text-sky-950 flex items-center gap-2">
        <Save className="w-4 h-4 text-sky-600 shrink-0" />
        <span>
          Vos notes sont automatiquement synchronisées et stockées localement dans votre navigateur pour chaque leçon.
        </span>
      </div>
    </div>
  );
};
